#!/bin/bash

source ~/.config/lemonbar/setup

while true; do
    echo "%{l}%{O 2}  $(volume)\
          %{c}$(workspace)\
          %{r}$(battery) $(network)$(ssid) %{O 2} $(_date) %{O 2} $(_time)  "
    sleep 1s
done |

lemonbar\
    eDP1 \
    -b\
    -g "x32"\
    -F "#ffffff"\
    -B "#19000000"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$ICON_FONT" | bash
