#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=28
PANEL_FONT_FAMILY="Sans Bold:size=10"
ICON_FONT="FontAwesome:size=14"
COLOR_BACKGROUND="#BEC4C7"
COLOR_BACKGROUND="#e9cc24"
COLOR_FOREGROUND="#000000"
COLOR_HIGHLIGHT="#000000"
COLOR_TEXT_HIGHLIGHT="#FFFFFF"
UPDATE="~/.config/lemonbar/update"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Countdown
count(){
	echo "$(~/dotfiles/scripts/countdown)"
}

#Music
music(){
	# song=$(mpc -p 6601 current)
	# echo -e '    '$song
	mpc -p 6601 current | zscroll -b "    "
}

music_control_left(){
	echo -e "%{A:mpc -p 6601 prev:}  %{A}"
}

music_control_right(){
	echo -e "%{A:mpc -p 6601 next:}  %{A}"
}

music_control_pause_play(){
	echo -e "%{A:mpc -p 6601 toggle:}  %{A}"
}

music_controls(){
	echo -e "$(music_control_left) $(music_control_pause_play) $(music_control_right)"
}

#Player
player(){
	status=$(mpc -p 6601 status | grep -E "(playing|paused)" -o)
	progress=$(mpc -p 6601 status | grep -E "(playing|paused)" | rev | cut -c 3- | rev | cut -d "(" -f 2)
	full=$((progress / 2))
	shade=$((50 - full))
	if [ $status == "playing" ]; then
		icon='  '
	else
		icon='  '
	fi
	# echo -e "%{A:mpc -p 6601 -q prev && ${UPDATE}:}  %{A}%{A:mpc -p 6601 -q toggle && ${UPDATE}:} " $icon " %{A}%{A:mpc -p 6601 -q next && ${UPDATE}:}  %{A} ▌"$(seq -s█ $full|tr -d '[:digit:]')$(seq -s▓ $shade|tr -d '[:digit:]')"▐"
	echo -e "%{A:mpc -p 6601 -q prev && ${UPDATE}:}  %{A}%{A:mpc -p 6601 -q toggle && ${UPDATE}:} " $icon " %{A}%{A:mpc -p 6601 -q next && ${UPDATE}:}  %{A}"
}