#!/bin/bash

source ~/.config/lemonbar/fixtop

while true; do
    echo "%{l}  $(music) \
    	  %{c}$(count) \
    	  %{r}$(player)   "
    sleep 1s
done |

lemonbar\
    eDP1 \
    -g "x32"\
    -F "#ffffff"\
    -B "#19000000"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$ICON_FONT" | bash