#!/bin/bash

source ~/.config/lemonbar/fixtop

{
line='                                                           '
zscroll -n -l 60 -b "%{l}      " -u "printf %q%q '$(mpc current -p 6601)''${line:$(echo $(mpc current -p 6601) | perl -nle "print length")}'" &
while true; do
    echo "%{c}$(count) \
        %{r}$(player)   "
    sleep 1s
done
} | 

lemonbar\
    eDP1 \
    -g "x32"\
    -F "#ffffff"\
    -B "#19000000"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$ICON_FONT" | bash