#!/bin/bash

source ~/.config/lemonbar/fixtop

{
# zscroll -l 20 -b "%{l}      " -u "mpc current -p 6601" &
while true; do
    echo "%{c}$(count) \
        %{r}$(player)   "
    sleep 1s
done
} |

lemonbar\
    eDP1 \
    -g "x32"\
    -F "#ffffff"\
    -B "#88000000"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$ICON_FONT" | bash
