#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=28
PANEL_FONT_FAMILY="Sans Bold:size=10"
ICON_FONT="FontAwesome:size=14"
COLOR_BACKGROUND="#BEC4C7"
COLOR_BACKGROUND="#e9cc24"
COLOR_FOREGROUND="#000000"
COLOR_HIGHLIGHT="#000000"
COLOR_TEXT_HIGHLIGHT="#FFFFFF"
UPDATE="~/.config/lemonbar/update"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


# Power button
power(){
	echo -e '%{A:oblogout:}    %{A}'
}

# Clock
clock(){
	echo -e '  ' $(date +'%A, %b %e')  '  ' $(date +'%l:%M %p') ' '
}

_date(){
	echo -e '  ' $(date +'%A, %b %e')
}

_time(){
	echo -e '  ' $(date +'%l:%M %p') ' '
}

# Battery
battery(){
	lvl=$(cat /sys/class/power_supply/BAT1/capacity)
	stat=$(cat /sys/class/power_supply/BAT1/status)
	if [ $stat == "Charging" ]
	then
		icon=' '
	elif (($lvl > 80))
	then
		icon=' '
	elif (($lvl > 60))
	then
		icon=' '
	elif (($lvl > 40))
	then
		icon=' '
	elif (($lvl > 20))
	then
		icon=' '
	else
		icon=' '
	fi

	echo -e $icon $lvl'%' ' '
}

# Networking
network(){
	wired=$(ip route get 8.8.8.8 | grep -Po 'dev \K\w+' | grep -qFf - /proc/net/wireless)
	if $wired; then
		icon=' '
		ssid=''
	else
		icon=' '
		ssid=$(iwgetid -r)
	fi
	echo -e $icon $ssid ' '
}

ssid(){
	name=$(iwgetid -r)
	echo $name
}

# Volume
volume(){
	vol=$(amixer get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}' | sed s/%//)
	if [ $vol = 0 ]; then
		icon=' '
	elif [ $vol -lt 33 ]; then
		icon=' '
	elif [ $vol -lt 66 ]; then
		icon=' '
	else
		icon=' '
	fi

	echo -e "%{A:amixer -q set Master 5+ && ${UPDATE}:}  %{A}\
					 %{A:amixer -q set Master 5- && ${UPDATE}:}  %{A}"\
					 '' $icon $vol'%' ' '
}

#Music
music(){
	song=$(mpc current)
	echo -e '  ' $song
}

music_control_left(){
	echo -e "%{A:mpc prev:}  %{A}"
}

music_control_right(){
	echo -e "%{A:mpc next:}  %{A}"
}

music_control_pause_play(){
	echo -e "%{A:mpc toggle:}  %{A}"
}

music_controls(){
	echo -e "$(music_control_left) $(music_control_pause_play) $(music_control_right)"
}

#Player
player(){
	status=$(mpc status | grep -E "(playing|paused)" -o)
	progress=$(mpc status | grep -E "(playing|paused)" | rev | cut -c 3- | rev | cut -d "(" -f 2)
	full=$((progress / 2))
	shade=$((50 - full))
	if [ $status == "playing" ]; then
		icon='  '
	else
		icon='  '
	fi
	echo -e "%{A:mpc -q prev && ${UPDATE}:}  %{A}%{A:mpc -q toggle && ${UPDATE}:} " $icon " %{A}%{A:mpc -q next && ${UPDATE}:}  %{A} ▌"$(seq -s█ $full|tr -d '[:digit:]')$(seq -s▓ $shade|tr -d '[:digit:]')"▐"
}

# Workspace
workspace() {

	wslist=$(\
		wmctrl -d \
		| awk '/ / {print $2 $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20}' ORS=''\
		| sed -e 's/\s*  / /g' \
		-e 's/*\b0\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b1\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b2\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b3\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b4\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b5\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b6\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b7\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b8\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/*\b9\b/%{F#FFffaa00}%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}%{F-}/g' \
		-e 's/-\b0\b//g' \
		-e 's/-\b1\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b2\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b3\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b4\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b5\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b6\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b7\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b8\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		-e 's/-\b9\b/%{A:i3-msg workspace & \&\& \~\/.config\/lemonbar\/update:}          %{A}/g' \
		| sed -e 's/workspace [-,*]/workspace /g'
	)

	if [[ $wslist == *""* ]]
	then
		echo -n -e "$wslist"
	else
		echo -n -e "%{A:i3-msg workspace 0 && ~/.config/lemonbar/update:}          %{A}$wslist"
	fi
}

title(){
	title=$(xdotool getactivewindow getwindowname)
	echo "$title" | cut -c 1-70
}

