#!/bin/sh
rofi \
-color-enabled \
-color-window "argb:F2112233, argb:00112233, argb:00112233" \
-color-normal "argb:0000000, #fff, argb:0000000, argb:00112233, #ff7733" \
-color-active "argb:0000000, #fff, argb:0000000, argb:00112233, #ff7733" \
-color-urgent "argb:0000000, #fff, argb:0000000, argb:00112233, #ff7733" \
-show run \
-location 0 \
-width 1920 \
-lines 4 \
-eh 2 \
-bw 0 \
-padding 486 \
-seperator-style none \
-font "Source Code Pro 18" \
