exa_api_key: ENC[AES256_GCM,data:KF+JnRT3l/Q0nf1mnqzOBcaA4Fc4qXbPzLvEZMv5u1dY0r8T,iv:CKy5mdNpkYOofgcQx57ENsa2jZJ9HgMbwRXRVW/TRgs=,tag:LwBolxzt09CGgAYneW9QMQ==,type:str]
sops:
    age:
        - recipient: age1cutjme0ql75hp2d5jsmlnlu966yhjfp8zvm47wktvk87j8nuldnss66e6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TytTMitWQ0doRFFCSzNX
            eDkyVWZOUmRlcUpGYlZRaldkSDJNNUNEQkZJCnJTejZvZ29Fa09nNDBDVklwbU8z
            ZmRFZXF0NS9TR3c3cEJkb3puTU5RYmcKLS0tIE5YVStCeFV5SVBkREdsWkM5d21P
            cEFacWcyWDJjU3hJcjFmb1JtNFRlaDAKVSSXgVIhpcMAN0Rt0I04oXoUyE2nHDLX
            SggBKlyaZJQ8+viX9BhMRNgkIuu0URWoRtliUcN91jqMF+5L2HLwsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T08:15:17Z"
    mac: ENC[AES256_GCM,data:cjs1T4CO6R3SmT9N30K4wi7gF56G4Ebq5WM24Zqo2JPCO59/ugDddRoYESAcQ8h2uTHojb02y8S45nDMBpxYLwd5RbYvbToJEnnUQdAm0XuhiCQLBgMJQg4gdbDJjOSZ9JV9Cm2Lo7q7imsyMm7MOJ4duLEAYZyHH88og4iySmM=,iv:QW++XnZ1VzXDuCHJZbSX+SK3nxpILerTBW6x1dRSsgU=,tag:ROwCc6Vjm52Ec+YIoey5Fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
