exa_api_key: ENC[AES256_GCM,data:KF+JnRT3l/Q0nf1mnqzOBcaA4Fc4qXbPzLvEZMv5u1dY0r8T,iv:CKy5mdNpkYOofgcQx57ENsa2jZJ9HgMbwRXRVW/TRgs=,tag:LwBolxzt09CGgAYneW9QMQ==,type:str]
glab_cfdata_token: ENC[AES256_GCM,data:U8Wux5GuMHzjN0qroN1SeEVaS7Gn6GrgKho=,iv:YqmcERHkI5fDzNEKVGHDV/IpFO6M6Tlx0pHwo1oYH48=,tag:3oTJADx9xgBmaBoUYUScCg==,type:str]
sops:
    age:
        - recipient: age1cutjme0ql75hp2d5jsmlnlu966yhjfp8zvm47wktvk87j8nuldnss66e6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TytTMitWQ0doRFFCSzNX
            eDkyVWZOUmRlcUpGYlZRaldkSDJNNUNEQkZJCnJTejZvZ29Fa09nNDBDVklwbU8z
            ZmRFZXF0NS9TR3c3cEJkb3puTU5RYmcKLS0tIE5YVStCeFV5SVBkREdsWkM5d21P
            cEFacWcyWDJjU3hJcjFmb1JtNFRlaDAKVSSXgVIhpcMAN0Rt0I04oXoUyE2nHDLX
            SggBKlyaZJQ8+viX9BhMRNgkIuu0URWoRtliUcN91jqMF+5L2HLwsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T17:13:53Z"
    mac: ENC[AES256_GCM,data:czDCNJwYKdPQWnMoJKowIX9kX7H2pBeQM0RdswPntwkgHFf6+4c42sMXzzFlCaYjsLMYVI4Le3oesNE/G992QISE0zzsfFoaQBueGwWb8WRJx99g1kDX+VZEyJvUjKe3m1ugkrmL+0ruh11fJAOAIWso0P8pd2AiQEXgYPpQC1Y=,iv:mcBNykl2pgAVelrUa+HWzTi0ECppLZnZeNVqP7uY+Pc=,tag:CNMd9/kOORIMgFyLDSrikQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
